# Generated by Django 4.2.26 on 2025-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CronTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Почта пользователя"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(max_length=50, verbose_name="Ник пользователя"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Включена"),
                ),
            ],
            options={
                "verbose_name": "Периодическая задача",
                "verbose_name_plural": "Периодические задачи",
                "db_table": "cron_tasks",
                "managed": False,
            },
        ),
    ]
