"""unique constraints

Revision ID: 3fe876f8e763
Revises: 8aaf7089b53b
Create Date: 2026-01-13 13:24:35.229457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe876f8e763'
down_revision = '8aaf7089b53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_card', 'user_cards', ['user_id', 'card_id'])
    op.create_unique_constraint('uq_user_deck', 'user_decks', ['user_id', 'deck_id'])
    op.create_unique_constraint('uq_user_leader', 'user_leaders', ['user_id', 'leader_id'])
    op.create_unique_constraint('uq_user_level', 'user_levels', ['user_id', 'level_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_level', 'user_levels', type_='unique')
    op.drop_constraint('uq_user_leader', 'user_leaders', type_='unique')
    op.drop_constraint('uq_user_deck', 'user_decks', type_='unique')
    op.drop_constraint('uq_user_card', 'user_cards', type_='unique')
    # ### end Alembic commands ###
