"""user_resources

Revision ID: b75de6c1a8b3
Revises: 639d00880e89
Create Date: 2026-01-08 15:13:29.177795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75de6c1a8b3'
down_revision = '639d00880e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraps', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('wood', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('kegs', sa.Integer(), server_default='3', nullable=False),
    sa.Column('big_kegs', sa.Integer(), server_default='1', nullable=False),
    sa.Column('chests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('keys', sa.Integer(), server_default='3', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resources')
    # ### end Alembic commands ###
