"""enemies and enemy leaders

Revision ID: 8ce99d743fcd
Revises: e1b846b68233
Create Date: 2026-01-06 18:08:49.393437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce99d743fcd'
down_revision = 'e1b846b68233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('base_hp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shield', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_field', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_deck', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_grave', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('passive_ability_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reset_timer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('each_tick', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_deathwish', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deathwish_id', sa.Integer(), nullable=True),
    sa.Column('deathwish_value', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deathwish_id'], ['deathwishes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passive_ability_id'], ['enemy_passive_abilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enemy_leaders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('base_hp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.Column('has_passive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('passive_ability_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reset_timer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('each_tick', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['enemy_leader_abilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passive_ability_id'], ['enemy_passive_abilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enemy_leaders')
    op.drop_table('enemies')
    # ### end Alembic commands ###
