# Generated by Django 4.2.26 on 2025-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Название события"
                    ),
                ),
                (
                    "processing",
                    models.JSONField(default=list, verbose_name="Конфиг события"),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "db_table": "events",
                "managed": False,
            },
        ),
    ]
